<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\products;
use App\Models\Products as ModelsProducts;
use Faker\Factory as Faker;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $faker = Faker::create();
        
        // for ($i = 0; $i < 50; $i++) {
        //     products::create([
        //         "name" => $faker->word,
        //         "image" => 'afonexh1.jpg',
        //         "color" => $faker->word,
        //         "price" => $faker->randomFloat(0,500000,900000),
        //         "price_sale" => $faker->randomFloat(0,500000,900000),
        //         "quantity" => $faker->numberBetween(10,100),
        //         "sold" => $faker->numberBetween(10,100),
        //         "view" => $faker->numberBetween(10,100),
        //         "category_id" => $faker->numberBetween(1,8)
        //     ]);
        // }

        Products::insert(
            [
                [
                  "id" => 1,
                  "name" => "Nike Air Force 1 Essential Trắng Nâu",
                  "image" => "afonetn1.jpg",
                  "color" => "Trắng Nâu",
                  "price" => 800000.00,
                  "price_sale" => null,
                  "quantity" => 42,
                  "sold" => 58,
                  "view" => 53,
                  "brand_id" => 1,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 2,
                  "name" => "Nike Air Force 1 Essential Xanh Hồng",
                  "image" => "afonexh1.jpg",
                  "color" => "Xanh Hồng",
                  "price" => 900000.00,
                  "price_sale" => 850000.00,
                  "quantity" => 61,
                  "sold" => 70,
                  "view" => 93,
                  "brand_id" => 1,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 3,
                  "name" => "Nike Air Force 1 Essential Xanh Xám",
                  "image" => "afonexx1.jpg",
                  "color" => "Xanh Xám",
                  "price" => 900000.00,
                  "price_sale" => 650000.00,
                  "quantity" => 26,
                  "sold" => 82,
                  "view" => 35,
                  "brand_id" => 1,
                  "category_id" => 3,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 4,
                  "name" => "Nike Air Force 1 Trắng Viền Đen",
                  "image" => "afonetvd1.jpg",
                  "color" => "Trắng Viền Đen",
                  "price" => 500000.00,
                  "price_sale" => null,
                  "quantity" => "4",
                  "sold" => 00,
                  "view" => 00,
                  "brand_id" => 1,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 5,
                  "name" => "Nike Air Force 1 Trắng Viền Xanh",
                  "image" => "afonetvx1.jpg",
                  "color" => "Trắng Viền Xanh",
                  "price" => 800000.00,
                  "price_sale" => 750000.00,
                  "quantity" => 45,
                  "sold" => 15,
                  "view" => 66,
                  "brand_id" => 1,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 6,
                  "name" => "Nike Air Force 1 Essential Full Xám",
                  "image" => "afonefx1.jpg",
                  "color" => "Full Xám",
                  "price" => 950000.00,
                  "price_sale" => 850000.00,
                  "quantity" => 68,
                  "sold" => 56,
                  "view" => 77,
                  "brand_id" => 1,
                  "category_id" => 3,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 7,
                  "name" => "Nike Air Force 1 Kem Đế Nâu",
                  "image" => "afonetn1.jpg",
                  "color" => "Kem Đế Nâu",
                  "price" => 900000.00,
                  "price_sale" => null,
                  "quantity" => 92,
                  "sold" => 90,
                  "view" => 95,
                  "brand_id" => 1,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 8,
                  "name" => "Nike Air Force 1 Kem Xanh Nhạt",
                  "image" => "afonekx1.jpg",
                  "color" => "Kem Xanh Nhạt",
                  "price" => 800000.00,
                  "price_sale" => null,
                  "quantity" => 45,
                  "sold" => 63,
                  "view" => 62,
                  "brand_id" => 1,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 9,
                  "name" => "Nike Air Force 1 Essential Trắng Đen",
                  "image" => "afoneetd1.jpg",
                  "color" => "Trắng Đen",
                  "price" => 850000.00,
                  "price_sale" => "800000.00",
                  "quantity" => 73,
                  "sold" => 70,
                  "view" => 33,
                  "brand_id" => 1,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 10,
                  "name" => "Nike Air Force 1 Essential Full Đen",
                  "image" => "afonefd1.jpg",
                  "color" => "Full Đen",
                  "price" => 600000.00,
                  "price_sale" => 550000.00,
                  "quantity" => 58,
                  "sold" => 54,
                  "view" => 98,
                  "brand_id" => 1,
                  "category_id" => 3,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 11,
                  "name" => "Adidas Alphabounce New 22 Đen Trắng",
                  "image" => "aandt1.jpg",
                  "color" => "Đen Trắng",
                  "price" => 750000.00,
                  "price_sale" => null,
                  "quantity" => 47,
                  "sold" => 16,
                  "view" => 88,
                  "brand_id" => 2,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 12,
                  "name" => "Adidas Alphabounce New 22 Full Trắng",
                  "image" => "aanft1.jpg",
                  "color" => "Full Trắng",
                  "price" => 550000.00,
                  "price_sale" => null,
                  "quantity" => 63,
                  "sold" => 85,
                  "view" => 77,
                  "brand_id" => 2,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 13,
                  "name" => "Adidas Alphabounce New 22 Ghi Trắng",
                  "image" => "aangt1.jpg",
                  "color" => "Ghi Trắng",
                  "price" => 750000.00,
                  "price_sale" => 650000.00,
                  "quantity" => 23,
                  "sold" => 99,
                  "view" => 30,
                  "brand_id" => 2,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 14,
                  "name" => "Adidas Alphabounce New 22 Kem Trắng",
                  "image" => "aankt1.jpg",
                  "color" => "Kem Trắng",
                  "price" => 750000.00,
                  "price_sale" => null,
                  "quantity" => 41,
                  "sold" => 69,
                  "view" => 65,
                  "brand_id" => 2,
                  "category_id" => 3,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 15,
                  "name" => "Adidas Alphabounce New 22 Trắng Navy",
                  "image" => "aantn1.jpg",
                  "color" => "Trắng Navy",
                  "price" => 700000.00,
                  "price_sale" => null,
                  "quantity" => 40,
                  "sold" => 50,
                  "view" => 54,
                  "brand_id" => 2,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 16,
                  "name" => "Adidas Alphabounce New Trắng Navy Đỏ",
                  "image" => "aantnd1.jpg",
                  "color" => "Trắng Navy Đỏ",
                  "price" => 750000.00,
                  "price_sale" => null,
                  "quantity" => 25,
                  "sold" => 76,
                  "view" => 66,
                  "brand_id" => 2,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 17,
                  "name" => "Adidas 8681 New 22 Đen Kẻ Trắng SF",
                  "image" => "a8681dkt1.jpg",
                  "color" => "Đen Kẻ Trắng",
                  "price" => 800000.00,
                  "price_sale" => null,
                  "quantity" => 65,
                  "sold" => 80,
                  "view" => 91,
                  "brand_id" => 2,
                  "category_id" => 3,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 18,
                  "name" => "Adidas 8681 New 22 Xanh Kẻ Trắng SF",
                  "image" => "a8681xkt1.jpg",
                  "color" => "Xanh Kẻ Trắng",
                  "price" => 650000.00,
                  "price_sale" => 600000.00,
                  "quantity" => 86,
                  "sold" => 59,
                  "view" => 59,
                  "brand_id" => 2,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 19,
                  "name" => "Giày LV Trainer Maxi Trắng Đen",
                  "image" => "lvtd1.jpg",
                  "color" => "Trắng Đen",
                  "price" => 750000.00,
                  "price_sale" => 680000.00,
                  "quantity" => 53,
                  "sold" => 47,
                  "view" => 34,
                  "brand_id" => 3,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 20,
                  "name" => "Giày LV Trainer Maxi Full Trắng",
                  "image" => "lvft1.jpg",
                  "color" => "Full Trắng",
                  "price" => 500000.00,
                  "price_sale" => null,
                  "quantity" => 83,
                  "sold" => 41,
                  "view" => 66,
                  "brand_id" => 3,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 21,
                  "name" => "Giày LV Trainer Maxi Trắng Navy",
                  "image" => "lvtn1.jpg",
                  "color" => "Trắng Navy",
                  "price" => 700000.00,
                  "price_sale" => null,
                  "quantity" => 99,
                  "sold" => 43,
                  "view" => 54,
                  "brand_id" => 3,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 22,
                  "name" => "Giày LV Trainer Maxi Trắng Nâu",
                  "image" => "lvtnau1.jpg",
                  "color" => "Trắng Nâu",
                  "price" => 680000.00,
                  "price_sale" => null,
                  "quantity" => 62,
                  "sold" => 36,
                  "view" => 30,
                  "brand_id" => 3,
                  "category_id" => 2,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 23,
                  "name" => "Giày LV Trainer Maxi Trắng Xám",
                  "image" => "lvtx1.jpg",
                  "color" => "Trắng Xám",
                  "price" => 900000.00,
                  "price_sale" => null,
                  "quantity" => 77,
                  "sold" => 87,
                  "view" => 51,
                  "brand_id" => 3,
                  "category_id" => 3,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 24,
                  "name" => "Giày LV Trainer Xanh Kẻ Trắng",
                  "image" => "lvtxk1.jpg",
                  "color" => "Xanh Kẻ Trắng",
                  "price" => 780000.00,
                  "price_sale" => 600000.00,
                  "quantity" => 28,
                  "sold" => 25,
                  "view" => 67,
                  "brand_id" => 3,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ],
                [
                  "id" => 25,
                  "name" => "Giày LV Trainer Maxi Trắng Đen 2",
                  "image" => "lvtd21.jpg",
                  "color" => "Trắng Đen",
                  "price" => 700000.00,
                  "price_sale" => null,
                  "quantity" => 58,
                  "sold" => 68,
                  "view" => 31,
                  "brand_id" => 3,
                  "category_id" => 1,
                  'created_at'=> now(),
                  'updated_at'=> now(),
                ]
            ]
        );
    }
}
